name: check-packer

on:
  push:
    branches: [main, HW4]
  workflow_dispatch:

jobs:

  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

  build:
    name: check-packer
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer --version
      
      - name: Pack the files
        run: packer init machine_image/packer/gcp.pkr.hcl
      
      - name: Packer Check Format
        run: |
          packer fmt machine_image/packer/gcp.pkr.hcl
          packer fmt -check machine_image/packer/gcp.pkr.hcl

      - name: Run Packer validate
        run: packer validate machine_image/packer/gcp.pkr.hcl