name: packer-runner

on:
  # Trigger the workflow on puill request and is merge
  # push:
  pull_request:
    types: [closed]
    branches: [main]
  
jobs:
  # job_id:
  #   # Add "id-token" with the intended permissions.
  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  build:
    name: packer-runner
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: 'Authenticate with Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Install Packer
        run: |
          wget https://releases.hashicorp.com/packer/1.7.4/packer_1.7.4_linux_amd64.zip
          unzip packer_1.7.4_linux_amd64.zip
          sudo mv packer /usr/local/bin
          packer --version
      
      - name: Create .env
        run: |
          touch .env
          sudo echo "PORT=${{ secrets.PORT }}" | sudo tee -a .env
          sudo echo "DB_HOST=${{ secrets.DB_HOST }}" | sudo tee -a .env
          sudo echo "DB_USER=${{ secrets.DB_USER }}" | sudo tee -a .env
          sudo echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee -a .env
          sudo echo "DB_NAME=${{ secrets.DB_NAME }}" | sudo tee -a .env
          sudo echo "DB_PORT=${{ secrets.DB_PORT }}" | sudo tee -a .env
          sudo echo "NODE_ENV=${{ secrets.NODE_ENV }}" | sudo tee -a .env
      
      - name: Zip the files
        run: zip -r webapp.zip . -x \\node_modules\\ \\.git\\ 

      # - name: Upload the zip file
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: webapp
      #     path: webapp.zip

      - name: Pack the files
        run: packer init machine_image/packer/gcp.pkr.hcl

      # - name: Set up GCP credentials
      #   uses: google-github-actions/setup-gcloud@v2
      #   with:
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     project_id: ${{ secrets.PROJECT_ID }}
      #     export_default_credentials: true

      # Use the GCP Credentials to run Packer build
      - name: Run Packer
        run: packer build -force -var 'project_id=${{ secrets.PROJECT_ID }}' -var 'image_family=${{ secrets.IMAGE_FAMILY}}' -var 'image_name=${{ secrets.IMAGE_NAME }}' -var 'zone=${{ secrets.ZONE }}' -var 'image_storage_locations=${{ secrets.IMAGE_STORAGE_LOCATIONS }}' machine_image/packer/gcp.pkr.hcl


      # - name: Run Packer
      #   run: packer build -var 'project_id=${{ secrets.PROJECT_ID }}' -var 'image_family=${{ secrets.IMAGE_FAMILY}}' -var 'source_image=${{ secrets.SOURCE_IMAGE }}' -var 'zone=${{ secrets.ZONE }}

